name: Simple Stock Analysis
on:
  workflow_dispatch:
jobs:
  run_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests google-generativeai tushare pandas numpy tavily-python
      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.gemini_api_key }}
          STOCK_LIST: ${{ secrets.stock_list }}
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
          STOCK_DATA_API_KEY: ${{ secrets.STOCK_DATA_API_KEY }}
          TAVILY_API_KEYS: ${{ secrets.TAVILY_API_KEYS }}
        run: |
          python main.py
